info:
  description: Spring Cloud Samples
  url: https://github.com/vedanshjaiswal16/newGitTest
  
secret-message: secret-messageFromConfigFromApplicationYmlAnother Test1
message: this property is form application.yml uploaded form git1
